---
title: "Sprawozdanie z pierwszego tygodnia"
date: "24 XI 2020"
output: pdf_document
---


# Wybrane zbiory danych

1. [ourworldindata.org/coronavirus](https://ourworldindata.org/coronavirus)

Źródło podstawowe z wieloma danymi na temat pandemii.

2. [aqicn.org/data-platform/covid19](https://aqicn.org/data-platform/covid19/?fbclid=IwAR1ta3cmXjcGRdwDYwBGcP4Unbyj3Z4sJkA-chvCtRJDV5SDvn_PRniIYS4)

Zbiór danych World Air Quality Index przedstawia wartości różnych wskaźników zanieczyszczeń, takich jak PM$_{10}$, a także informacje meteorologiczne z danego dnia. Dane są zbierane w większych miastach na całym świecie.

3. [covid19.apple.com/mobility](https://covid19.apple.com/mobility?fbclid=IwAR2E-U7UEvbENdhjq28y1EhL9EbelPBs5s0SbKaiYrM1K9gzbHpviYd9K3U)

Zbiór danych zawierający raporty o trendach mobilności związane z COVID-19. Odzwierciedlają one zapytania o wskazówki dojazdu w Mapach Apple według środka transportu w wielu krajach.

# Postawione pytania

1. Co pandemia zmieniła na lepsze?
Przyjrzenie się pozytywnym efektom obecnej sytuacji.

2. Czy liczba wypadków i kolizji drogowych zmalała?
Sprawdzenie wpływu epidemii na sytuację na drogach.

3. Czy zanieczyszczenie powietrza zmalało?
Zbadanie zależności pomiędzy pandemią a obecnością zanieczyszczeń w miastach.
